### ISSUE TITLE
Record open in Xplore doesn't work

### ISSUE THREAD

**Issue by themrvideouser** [macmorning/snowtools-webext#70] opened 2020-02-26 12:25 UTC
If you have addon enabled and want to open a record e.g. Incident in Xplore the record and sys_id doesn't get auto populated

**Comment by macmorning** [comment] 2020-02-26 20:03
Are we talking about [this Xplore](https://developer.servicenow.com/app.do#!/share/contents/9650888_xplore_developer_toolkit?v=4.05&t=PRODUCT_DETAILS)?
I'm not sure how the extension could interfere with this app because we hardly touch the DOM and we don't inject code into the page.
Can you confirm you disabled the extension to make sure it's related?
Also, please post steps to reproduce.

Thx!

**Comment by macmorning** [comment] 2020-03-05 11:35
Not enough input, I'm closing the issue. Let me know if you can give more informations.

**Closed by macmorning** 2020-03-05 11:35 UTC
